---
- hosts: localhost
  pre_tasks:
    - name: Ensure that the app is running
      uri:
        url: http://localhost:80
  roles:
  - {
      role: docker_operations,
      docker_operation: stop_container,
      container_name: webapp_weba_1
    }
  post_tasks:
    - pause:
        seconds: 5
    - name: Test the App server failover
      uri:
        url: http://localhost:80
    - name: Verify the heartbeat of the killed container
      uri:
        url: http://localhost:8081/api/v1.3/docker/webapp_weba_1
        status_code: 500
        return_content: yes
      register: result
    - name: Throw alert if no heartbeat detected
      debug:
        msg: "Triggering the alert for the Container webapp_weba_1"
      when: "'failed to get Docker container' in result.content"
