version: "2"
services:
  weba:
    build: .
    expose:
      - "80"
      - "27017"
    depends_on:
      - mongo
  webb:
    build: .
    expose:
      - "80"
      - "27017"
    depends_on:
      - mongo
  mongo:
    image: mongo:3.4.0
    volumes:
      - $HOME/ghc/mongodata:/data/db
    ports:
      - "mongodb:27017:27017"
  mongo-seed:
    build: ./mongo-seed
    links:
      - mongo
  haproxy:
    image: hypriot/rpi-haproxy
    #image: haproxytech/haproxy-ubuntu 
    volumes:
       - ./haproxy:/haproxy-override
    links:
      - weba
      - webb
      - mongo
    ports:
      - "80:80"
      - "70:70"
    expose:
       - "80"
       - "70"
